### ISSUE TITLE
Extend to take generic graph/tree as table input - to rewrite to standard validation input table (subject object pairs)

### ISSUE THREAD

**Issue by dosumis** [INCATools/relation-validator#9]
e.g. 

Organ_Level_1 | Anatomical_Level_2 | Anatomical_Level_3 | Anatomical_Level_4
-- | -- | -- | --
Brain | Forebrain | Diencephalon | Prethalamus
Brain | Forebrain | Diencephalon | Hypothalamus
Brain | Forebrain | Diencephalon | Subthalamus

**Comment by anitacaron** [comment]
Can the table have the ontology terms on the left side?

| Organ_Level_1 ID | Organ_Level_1 | Anatomical_Level_2 ID | Anatomical_Level_2 | Anatomical_Level_3 ID | Anatomical_Level_3 | Anatomical_Level_4 ID | Anatomical_Level_4 |
|------------------|---------------|-----------------------|--------------------|-----------------------|--------------------|-----------------------|--------------------|
| UBERON:0000955   | Brain         | UBERON:0001890        | Forebrain          | UBERON:000189         | Diencephalon       | UBERON:0001900        | Prethalamus        |
| UBERON:0000955   | Brain         | UBERON:0001890        | Forebrain          | UBERON:000189         | Diencephalon       | UBERON:0001898        | Hypothalamus       |
| UBERON:0000955   | Brain         | UBERON:0001890        | Forebrain          | UBERON:000189         | Diencephalon       | UBERON:0001900        | Subthalamus        |
